### ISSUE TITLE
PositionSpell/SelfcastSpell/TargettedSpell don't exist.

### ISSUE THREAD

**Issue by nullopt** [SharpGG/Core#1]
Those classes no longer exist in this version.

**Comment by SopranoSharp** [comment]
These classes never existed.
In my examples, I created dummy classes in my project for this. I will do the same for the core.

**Comment by rman200** [comment]
It might have been intentional as they only released Interfaces, not implementations.

`await this._control.Spell.Cast(SpellSlot.Q, new SelfCastSpell()); // Self cast Q`
From the example we see SelfCastSpell() is Instantiable (Which, AFAIK, an interface isnt)

**Comment by SopranoSharp** [comment]
https://github.com/SharpGG/Core/pull/11
