### ISSUE TITLE
Give each exception category its own exception supertype, removing InvalidOperationException from the hiearchy

### ISSUE THREAD

**Issue by foundry27** [SharpGG/Core#5]
As it stands, every exception in Sharp.Core.Data.Exception.* inherits from System.Exception (pending changes, each exception is meant to extend System.InvalidOperationException at the time of writing). While packages like Exception.Control.Ping and Exception.Control.Spell have several spell and ping related exception classes within, there is no real _structural_ relationship between any of those classes because they are each there own little offshoot of InvalidOperationException, despite each of those classes existing in their own specific package, _logically_ relating them to one another. If a developer wants to handle a specific category of exceptions in their code (with category in this case meaning exceptions that come from a common package like Exception.Control.Spell or Exception.Control.Ping), the two options they have both have issues:

The first, and most subtly dangerous option, is to catch the superclass of each exception in the category you wish to deal with. In this case, that superclass is InvalidOperationException, one of the built-in system exception types. Catching universal exception types (which InvalidOperationException qualifies as, since every exception in the #GG API extends it) is general frowned upon because it can result in catching exceptions you didn't _really_ mean to catch, such as exceptions from library code or unrelated exceptions from logically separate parts of your program, like Pinging. One could argue that this ambiguity could be avoided by wrapping each set of related statements in their own try-catch blocks, but if there are unrelated statements that have to be executed between each other, this results in many try-catch blocks crammed in one after another, reducing the legibility of the code.

Speaking of legibility, the second, and by far the most visually unappealing option, is to catch every single possible exception subtype that exists in a specific exception category. In the case of spell casts, that would mean catching (at the time of writing) InvalidSpellTypeException, SpellNotAvailableException, and SpellOnCooldownException. Some (myself included!) would argue that there is nothing wrong with catching the most specific exception possible when you know you don't care about anything else, but in the case of a developer who simply wants to know what _kind_ of error occurred but not _how_ it happened, having to use multiple catch blocks over and over again can just be an eyesore.

I submit that each exception category should have its own category-specific supertype, such as a SpellCastException for Exception.Control.Spell, a PingException for Exception.Control.Ping, a ChatMessageException for Exception.Control.Chat, and so on. This is a commonly-accepted industry best practice for creating categories of exceptions that have some meaning to being handled generically, and is adhered to in both the C# (see: System.Data.DataException, System.MemberAccessException) and Java (see: java.lang.IllegalStateException, java.lang.reflect.ReflectiveOperationException) standard libraries. In doing this, users retain the ability to handle specific exceptions as necessary for their code while simultaneously avoiding the issues involved in needing to catch a universal exception type to handle specific categories of issues.

**Comment by SopranoSharp** [comment]
I am currently working on a solution to this.

**Comment by SopranoSharp** [comment]
https://github.com/SharpGG/Core/pull/9
